//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class ActivityTable : BaseTxtTable<ActivityTable>
{
    
    public string XlsxMapping = "Activity.xlsx";
    
    /// <summary>
    /// 主键
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 活动具体玩法类型
    /// </summary>
    public int Type;
    
    /// <summary>
    /// 扩展参数
    /// </summary>
    public string Extend;
    
    /// <summary>
    /// 玩家等级
    /// </summary>
    public string Level;
    
    /// <summary>
    /// 传送NPC
    /// </summary>
    public int Npc;
    
    /// <summary>
    /// 传送区域
    /// </summary>
    public int BornRegion;
    
    /// <summary>
    /// 面板
    /// </summary>
    public string Panel;
    
    /// <summary>
    /// 开启日期
    /// </summary>
    public string Week;
    
    /// <summary>
    ///  开启的具体天数
    /// </summary>
    public int Day;
    
    /// <summary>
    /// 每月第几周星期几
    /// </summary>
    public string Weekday;
    
    /// <summary>
    /// 活动周期
    /// </summary>
    public int Interval;
    
    /// <summary>
    /// 活动开始时间
    /// </summary>
    public string StartTime;
    
    /// <summary>
    /// 持续时间
    /// </summary>
    public int Duration;
    
    /// <summary>
    /// 入口持续时间
    /// </summary>
    public int EnterDuration;
    
    /// <summary>
    /// 完成次数
    /// </summary>
    public int Count;
    
    /// <summary>
    /// 活动描述
    /// </summary>
    public string Desc;
    
    /// <summary>
    /// 实际奖励
    /// </summary>
    public string RewardDesc;
    
    /// <summary>
    /// 是否开启提醒
    /// </summary>
    public int Remind;
    
    /// <summary>
    /// 是否公告
    /// </summary>
    public int Announce;
    
    /// <summary>
    /// 活动界面显示ICON
    /// </summary>
    public string ActivityIcon;
    
    /// <summary>
    /// 活动字体
    /// </summary>
    public string ActivityZiti;
    
    /// <summary>
    /// 事件引用
    /// </summary>
    public string QuoteEvent;
    
    public override int GetID()
    {
return ID ;
    }
}
