//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class ActorTable : BaseTxtTable<ActorTable>
{
    
    public string XlsxMapping = "Actor.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 现在是否开放
    /// </summary>
    public int Open;
    
    /// <summary>
    /// 职业
    /// </summary>
    public int Profession;
    
    /// <summary>
    /// 职业名称
    /// </summary>
    public string ProfessionName;
    
    /// <summary>
    /// 种族
    /// </summary>
    public int Race;
    
    /// <summary>
    /// 种族名称
    /// </summary>
    public string RaceName;
    
    /// <summary>
    /// 性别
    /// </summary>
    public int Sex;
    
    /// <summary>
    /// 角色职业图标
    /// </summary>
    public string CharaIcon;
    
    /// <summary>
    /// 职业特色描述
    /// </summary>
    public string Feature;
    
    /// <summary>
    /// 随机名字库姓
    /// </summary>
    public string Name1;
    
    /// <summary>
    /// 随即名字库名
    /// </summary>
    public string Name2;
    
    /// <summary>
    /// 武器
    /// </summary>
    public string Weapon;
    
    /// <summary>
    /// 初始外观
    /// </summary>
    public string ResId;
    
    /// <summary>
    /// 展示动作
    /// </summary>
    public string DisplayAction;
    
    /// <summary>
    /// 对应音效
    /// </summary>
    public string MainLanguage;
    
    /// <summary>
    /// 主动技能
    /// </summary>
    public string Skill;
    
    /// <summary>
    /// 角色初始头像
    /// </summary>
    public string InitialHead;
    
    /// <summary>
    /// 初始出生地图
    /// </summary>
    public int MapId;
    
    public override int GetID()
    {
return ID ;
    }
}
