//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class AppearanceTable : BaseTxtTable<AppearanceTable>
{
    
    public string XlsxMapping = "Appearance.xlsx";
    
    /// <summary>
    /// 外观ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 对应外观
    /// </summary>
    public string AppearanceRes;
    
    /// <summary>
    /// 是否有蒙皮信息
    /// </summary>
    public int Skin;
    
    public override int GetID()
    {
return ID ;
    }
}
