//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class BossTable : BaseTxtTable<BossTable>
{
    
    public string XlsxMapping = "BOSS.xlsx";
    
    /// <summary>
    /// Boss的ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// BOSS所属等级段
    /// </summary>
    public string Level;
    
    /// <summary>
    /// BOSS分类
    /// </summary>
    public int Type;
    
    /// <summary>
    /// BOSS名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// BOSS背景资源
    /// </summary>
    public string Bg;
    
    /// <summary>
    /// 击杀奖励预览
    /// </summary>
    public string Consume;
    
    /// <summary>
    /// 击杀奖励
    /// </summary>
    public int Award;
    
    /// <summary>
    /// 击杀奖励邮件
    /// </summary>
    public int Mail;
    
    /// <summary>
    /// 排名奖励
    /// </summary>
    public string Award1;
    
    /// <summary>
    /// 排名奖励邮件
    /// </summary>
    public int Mail1;
    
    /// <summary>
    /// 参与奖励
    /// </summary>
    public int Award2;
    
    /// <summary>
    /// 参与邮件
    /// </summary>
    public int Mail2;
    
    /// <summary>
    /// 界面动作
    /// </summary>
    public string Action;
    
    public override int GetID()
    {
return ID ;
    }
}
