//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class BuffTable : BaseTxtTable<BuffTable>
{
    
    public string XlsxMapping = "Skill.xlsx";
    
    /// <summary>
    /// buff的ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 描述
    /// </summary>
    public string Describe;
    
    /// <summary>
    /// 是否增益
    /// </summary>
    public int Gain;
    
    /// <summary>
    /// 类型
    /// </summary>
    public int ShareType;
    
    /// <summary>
    /// 类型
    /// </summary>
    public int BuffTriggerType;
    
    /// <summary>
    /// 叠加方式
    /// </summary>
    public int OverlayWay;
    
    /// <summary>
    /// 可叠加层数
    /// </summary>
    public string Number;
    
    /// <summary>
    /// 互斥
    /// </summary>
    public string Mutual;
    
    /// <summary>
    /// 延迟时间（毫秒）
    /// </summary>
    public int DelayTime;
    
    /// <summary>
    /// 持续时间（毫秒）
    /// </summary>
    public string ContinueTime;
    
    /// <summary>
    /// 间隔时间（毫秒）
    /// </summary>
    public int IntervalTime;
    
    /// <summary>
    /// 触发概率（万分率）
    /// </summary>
    public string TriggerProbability;
    
    /// <summary>
    /// 删除机制
    /// </summary>
    public string Delete;
    
    /// <summary>
    /// 显示顺序
    /// </summary>
    public int Order;
    
    /// <summary>
    /// 是否显示BUFF图标
    /// </summary>
    public int Broadcast;
    
    /// <summary>
    /// buff图标
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// buff特效
    /// </summary>
    public int effect;
    
    /// <summary>
    /// 动作效果ID
    /// </summary>
    public string SpecialResultId;
    
    /// <summary>
    /// 属性参数
    /// </summary>
    public string ResultId;
    
    /// <summary>
    /// 特殊效果类型
    /// </summary>
    public string ResultType;
    
    public override int GetID()
    {
return ID ;
    }
}
