//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class CardTable : BaseTxtTable<CardTable>
{
    
    public string XlsxMapping = "Card.xlsx";
    
    /// <summary>
    /// ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 卡片描述
    /// </summary>
    public string ShortDescribe;
    
    /// <summary>
    /// 技能1描述
    /// </summary>
    public string SkillShortDes;
    
    /// <summary>
    /// 同类
    /// </summary>
    public string Similar;
    
    /// <summary>
    /// 卡片星级
    /// </summary>
    public int CardLevel;
    
    /// <summary>
    /// 品质
    /// </summary>
    public int CardQuality;
    
    /// <summary>
    /// 基础属性
    /// </summary>
    public string CardBasic;
    
    /// <summary>
    /// 基础属性增量
    /// </summary>
    public string BasicInc;
    
    /// <summary>
    /// 助战技能1
    /// </summary>
    public string CardSkill;
    
    /// <summary>
    /// 助战技能1增量
    /// </summary>
    public string SkillInc;
    
    /// <summary>
    /// 技能1开启星级
    /// </summary>
    public int SkillOpen;
    
    /// <summary>
    /// 技能1描述
    /// </summary>
    public string SkillDes;
    
    /// <summary>
    /// 助战技能2
    /// </summary>
    public string CardSkillTwo;
    
    /// <summary>
    /// 助战技能2增量
    /// </summary>
    public string SkillIncTwo;
    
    /// <summary>
    /// 技能2开启星级
    /// </summary>
    public int SkillTwoOpen;
    
    /// <summary>
    /// 技能2描述
    /// </summary>
    public string SkillTwoDes;
    
    /// <summary>
    /// 专属碎片
    /// </summary>
    public string ExcDebris;
    
    /// <summary>
    /// 升级总数
    /// </summary>
    public string Total;
    
    /// <summary>
    /// 升级条件
    /// </summary>
    public string Number;
    
    /// <summary>
    /// 升级卡片
    /// </summary>
    public int NextID;
    
    /// <summary>
    /// 头像icon
    /// </summary>
    public string HeadIcon;
    
    /// <summary>
    /// 半身图
    /// </summary>
    public string BodyIcon;
    
    public override int GetID()
    {
return ID ;
    }
}
