//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class CollisionTable : BaseTxtTable<CollisionTable>
{
    
    public string XlsxMapping = "Skill.xlsx";
    
    /// <summary>
    /// 碰撞ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 起效时间
    /// </summary>
    public int Delay;
    
    /// <summary>
    /// 单次伤害
    ///持续时间
    /// </summary>
    public int DamgeTime;
    
    /// <summary>
    /// 攻击次数
    /// </summary>
    public int Degree;
    
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public int Interval;
    
    /// <summary>
    /// 搜索目标
    /// </summary>
    public string SearchTarget;
    
    /// <summary>
    /// 范围
    /// </summary>
    public string Scope;
    
    /// <summary>
    /// 搜索方式
    /// </summary>
    public int SearchMode;
    
    /// <summary>
    /// 目标数量
    /// </summary>
    public int count;
    
    /// <summary>
    /// 受击特效
    /// </summary>
    public int HitEffect;
    
    /// <summary>
    /// 命中音效
    /// </summary>
    public string HitSound;
    
    /// <summary>
    /// 自己BUFF
    /// </summary>
    public string SelfBuffId;
    
    /// <summary>
    /// 友方BUFF
    /// </summary>
    public string FriendBuffId;
    
    /// <summary>
    /// 敌方BUFF
    /// </summary>
    public string EnemyBuffId;
    
    /// <summary>
    /// 自己伤害
    /// </summary>
    public int SelfHurtID;
    
    /// <summary>
    /// 友方伤害
    /// </summary>
    public int FriendHurtID;
    
    /// <summary>
    /// 敌方伤害
    /// </summary>
    public int EnemyHurtID;
    
    public override int GetID()
    {
return ID ;
    }
}
