//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class DisplacementTable : BaseTxtTable<DisplacementTable>
{
    
    public string XlsxMapping = "Skill.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 能否移动
    /// </summary>
    public int Move;
    
    /// <summary>
    /// 移动方式
    /// </summary>
    public int MoveWay;
    
    /// <summary>
    /// 碰到目标
    /// </summary>
    public int KnockTarget;
    
    /// <summary>
    /// 移动位置
    /// </summary>
    public int Position;
    
    /// <summary>
    /// 距离
    /// </summary>
    public float TargetDistance;
    
    /// <summary>
    /// 移动延迟时间
    /// </summary>
    public int DeTime;
    
    /// <summary>
    /// 移动速度
    /// </summary>
    public int Speed;
    
    /// <summary>
    /// 移动最大距离
    /// </summary>
    public float MaxDistance;
    
    public override int GetID()
    {
return ID ;
    }
}
