//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class DropGroupTable : BaseTxtTable<DropGroupTable>
{
    
    public string XlsxMapping = "Drop.xlsx";
    
    /// <summary>
    /// 掉落组ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 职业
    /// </summary>
    public int Job;
    
    /// <summary>
    /// 性别
    /// </summary>
    public int Sex;
    
    /// <summary>
    /// 等级下限
    /// </summary>
    public int LevelDown;
    
    /// <summary>
    /// 等级上限
    /// </summary>
    public int LevelUp;
    
    /// <summary>
    /// 任务ID
    /// </summary>
    public int TaskID;
    
    /// <summary>
    /// 掉落概率
    /// </summary>
    public int Probability;
    
    /// <summary>
    /// 掉落ID
    /// </summary>
    public string DropID;
    
    /// <summary>
    /// 次数最小值
    /// </summary>
    public int NumberMin;
    
    /// <summary>
    /// 次数最大值
    /// </summary>
    public int NumMax;
    
    /// <summary>
    /// 次数上限
    /// </summary>
    public int NumLimit;
    
    public override int GetID()
    {
return ID ;
    }
}
