//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class DropTable : BaseTxtTable<DropTable>
{
    
    public string XlsxMapping = "Drop.xlsx";
    
    /// <summary>
    /// 掉落ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 掉落概率
    /// </summary>
    public int Probability;
    
    /// <summary>
    /// 物品ID
    /// </summary>
    public int ItemID;
    
    /// <summary>
    /// 最小值
    /// </summary>
    public int NumMin;
    
    /// <summary>
    /// 最大值
    /// </summary>
    public int NumMax;
    
    /// <summary>
    /// 时限类型
    /// </summary>
    public int TimeLimit;
    
    public override int GetID()
    {
return ID ;
    }
}
