//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class DungeonTable : BaseTxtTable<DungeonTable>
{
    
    public string XlsxMapping = "Dungeon.xlsx";
    
    /// <summary>
    /// 副本id
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 副本名称
    /// </summary>
    public string DungeonName;
    
    /// <summary>
    /// 退出区域
    /// </summary>
    public int QuitRegion;
    
    /// <summary>
    /// 功能类型
    /// </summary>
    public int FuncType;
    
    /// <summary>
    /// 扩展参数
    /// </summary>
    public string Extend;
    
    /// <summary>
    /// 副本时间
    /// </summary>
    public int DengeonTime;
    
    /// <summary>
    /// 进入人数
    /// </summary>
    public string Number;
    
    /// <summary>
    /// 开放日期
    /// </summary>
    public string OpenDays;
    
    /// <summary>
    /// 开放时间
    /// </summary>
    public string OpenTime;
    
    /// <summary>
    /// 次数
    /// </summary>
    public string Count;
    
    /// <summary>
    /// 进入消耗
    /// </summary>
    public string Consume;
    
    /// <summary>
    /// 通关奖励
    /// </summary>
    public string Reward;
    
    /// <summary>
    /// 副本描述
    /// </summary>
    public string Description;
    
    /// <summary>
    /// 事件引用
    /// </summary>
    public string QuoteEvent;
    
    public override int GetID()
    {
return ID ;
    }
}
