//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class DungeoneventTable : BaseTxtTable<DungeoneventTable>
{
    
    public string XlsxMapping = "DungeonEvent.xlsx";
    
    /// <summary>
    /// 主键
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 阶段描述
    /// </summary>
    public string StepDesc;
    
    /// <summary>
    /// 触发类型
    /// </summary>
    public int TriggerType;
    
    /// <summary>
    /// 触发参数
    /// </summary>
    public string TriggerParam;
    
    /// <summary>
    /// 事件类型
    /// </summary>
    public int EventType;
    
    /// <summary>
    /// 延迟时间(毫秒)
    /// </summary>
    public int Delay;
    
    /// <summary>
    /// 事件相关参数
    /// </summary>
    public string Effect;
    
    /// <summary>
    /// 重复次数
    /// </summary>
    public int Repeat;
    
    /// <summary>
    /// 事件重复时间间隔（毫秒）
    /// </summary>
    public int Interval;
    
    /// <summary>
    /// 结束之后添加事件
    /// </summary>
    public string AddEvent;
    
    /// <summary>
    /// 飘字
    /// </summary>
    public string Dialog;
    
    public override int GetID()
    {
return ID ;
    }
}
