//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class EffectDataTable : BaseTxtTable<EffectDataTable>
{
    
    public string XlsxMapping = "Effect.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 对应特效
    /// </summary>
    public string Path;
    
    /// <summary>
    /// 特效类型
    /// </summary>
    public string Type;
    
    /// <summary>
    /// 特效绑定
    /// </summary>
    public int Move;
    
    /// <summary>
    /// 特效延迟
    /// </summary>
    public float SpecialDelay;
    
    /// <summary>
    /// 存活时间
    /// </summary>
    public int Time;
    
    /// <summary>
    /// 偏移X,Y,Z
    /// </summary>
    public string Position;
    
    public override int GetID()
    {
return ID ;
    }
}
