//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class EquipSuitTable : BaseTxtTable<EquipSuitTable>
{
    
    public string XlsxMapping = "Item.xlsx";
    
    /// <summary>
    /// 套装ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 套装名称
    /// </summary>
    public string SuitName;
    
    /// <summary>
    /// 套装需要部位
    /// </summary>
    public string Part;
    
    /// <summary>
    /// 穿戴件数
    /// </summary>
    public int Count;
    
    /// <summary>
    /// 件数套装属性
    /// </summary>
    public string SuitAttr;
    
    /// <summary>
    /// 穿戴件数1
    /// </summary>
    public int Count1;
    
    /// <summary>
    /// 件数套装属性1
    /// </summary>
    public string SuitAttr1;
    
    public override int GetID()
    {
return ID ;
    }
}
