//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class EquipTable : BaseTxtTable<EquipTable>
{
    
    public string XlsxMapping = "Item.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 部位
    /// </summary>
    public int PartType;
    
    /// <summary>
    /// 部位名称
    /// </summary>
    public string PartName;
    
    /// <summary>
    /// 装备基础属性
    /// </summary>
    public string PrimaryAttribute;
    
    /// <summary>
    /// 附加属性条数
    /// </summary>
    public string Number;
    
    /// <summary>
    /// 附加属性库
    /// </summary>
    public string AdditionAttr;
    
    /// <summary>
    /// 是否有套装属性
    /// </summary>
    public int SuitAttr;
    
    /// <summary>
    /// 套装ID
    /// </summary>
    public int SuitId;
    
    public override int GetID()
    {
return ID ;
    }
}
