//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class EquipRecastTable : BaseTxtTable<EquipRecastTable>
{
    
    public string XlsxMapping = "EquipForge.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 最小等级
    /// </summary>
    public int MinLevel;
    
    /// <summary>
    /// 最大等级
    /// </summary>
    public int MaxLevel;
    
    /// <summary>
    /// 普通重铸银币消耗
    /// </summary>
    public int Silver;
    
    /// <summary>
    /// 普通重铸物品消耗
    /// </summary>
    public string Item;
    
    /// <summary>
    /// 普通重铸属性浮动最小值
    /// </summary>
    public int MinAttr;
    
    /// <summary>
    /// 普通重铸属性浮动最大值
    /// </summary>
    public int MaxAttr;
    
    /// <summary>
    /// 可加锁属性条数
    /// </summary>
    public int Lock;
    
    /// <summary>
    /// 高级重铸银币消耗
    /// </summary>
    public int ExpertSilver;
    
    /// <summary>
    /// 高级重铸物品消耗
    /// </summary>
    public string ExpertItem;
    
    /// <summary>
    /// 高级重铸属性浮动最小值
    /// </summary>
    public int ExpertMinAttr;
    
    /// <summary>
    /// 高级重铸属性浮动最大值
    /// </summary>
    public int ExpertMaxAttr;
    
    /// <summary>
    /// 高级重铸可加锁属性条数
    /// </summary>
    public int ExpertLock;
    
    public override int GetID()
    {
return ID ;
    }
}
