//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class EquipForgeTable : BaseTxtTable<EquipForgeTable>
{
    
    public string XlsxMapping = "EquipForge.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 职业大类
    /// </summary>
    public int Job;
    
    /// <summary>
    /// 等级小类
    /// </summary>
    public int Level;
    
    /// <summary>
    /// 打造部位
    /// </summary>
    public int Patr;
    
    /// <summary>
    /// 界面显示icon
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// 打造装备描述
    /// </summary>
    public string Des;
    
    /// <summary>
    /// 打造银币消耗
    /// </summary>
    public int Consume;
    
    /// <summary>
    /// 普通打造材料
    /// </summary>
    public string LowForge;
    
    /// <summary>
    /// 普通打造产出
    /// </summary>
    public string LowEquip;
    
    /// <summary>
    /// 强化打造附加材料
    /// </summary>
    public string LoudhighForge;
    
    /// <summary>
    /// 强化打造产出
    /// </summary>
    public string LoudhighEquip;
    
    /// <summary>
    /// 祝福值上限
    /// </summary>
    public int Wish;
    
    /// <summary>
    /// 单次打造获得祝福值
    /// </summary>
    public int Once;
    
    public override int GetID()
    {
return ID ;
    }
}
