//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class FactionArchitectureTable : BaseTxtTable<FactionArchitectureTable>
{
    
    public string XlsxMapping = "Faction.xlsx";
    
    /// <summary>
    /// ID索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 建筑类型
    /// </summary>
    public int Type;
    
    /// <summary>
    /// 建筑名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 建筑功能描述
    /// </summary>
    public string Des;
    
    /// <summary>
    /// 建筑图片展示
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// 建筑模型展示
    /// </summary>
    public string Model;
    
    /// <summary>
    /// 等级
    /// </summary>
    public int Level;
    
    /// <summary>
    /// 下一级
    /// </summary>
    public int NextLevel;
    
    /// <summary>
    /// 升级需其他建筑条件
    /// </summary>
    public string LevelUp;
    
    /// <summary>
    /// 升级需求文字描述
    /// </summary>
    public string Text;
    
    /// <summary>
    /// 升级消耗1
    /// </summary>
    public int LvExpend1;
    
    /// <summary>
    /// 升级消耗2
    /// </summary>
    public int LvExpend2;
    
    /// <summary>
    /// 升级效果1
    /// </summary>
    public int Result1;
    
    /// <summary>
    /// 升级效果2
    /// </summary>
    public int Result2;
    
    /// <summary>
    /// 升级效果3
    /// </summary>
    public int Result3;
    
    /// <summary>
    /// 升级效果4
    /// </summary>
    public int Result4;
    
    /// <summary>
    /// 升级效果5
    /// </summary>
    public int Result5;
    
    public override int GetID()
    {
return ID ;
    }
}
