//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class FashionTable : BaseTxtTable<FashionTable>
{
    
    public string XlsxMapping = "Item.xlsx";
    
    /// <summary>
    /// 外观ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 是否可染色
    /// </summary>
    public int Dye;
    
    /// <summary>
    /// 对应颜色ICON
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// 对应的外观资源
    /// </summary>
    public int AppearanceRes;
    
    /// <summary>
    /// 解锁消耗类型
    /// </summary>
    public int ConsumeType;
    
    /// <summary>
    /// 对应消耗参数
    /// </summary>
    public string Consume;
    
    /// <summary>
    /// 染色银币消耗
    /// </summary>
    public int Silver;
    
    /// <summary>
    /// 时限
    /// </summary>
    public int TimeLimit;
    
    public override int GetID()
    {
return ID ;
    }
}
