//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class FindpathTable : BaseTxtTable<FindpathTable>
{
    
    public string XlsxMapping = "Findpath.xlsx";
    
    /// <summary>
    /// 地图ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 类型
    /// </summary>
    public int Type;
    
    /// <summary>
    /// 详细类型
    /// </summary>
    public int Detailed;
    
    /// <summary>
    /// 所在地图
    /// </summary>
    public int Map;
    
    /// <summary>
    /// 所在地图坐标
    /// </summary>
    public string Xyz;
    
    public override int GetID()
    {
return ID ;
    }
}
