//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class GameShopTable : BaseTxtTable<GameShopTable>
{
    
    public string XlsxMapping = "GameShop.xlsx";
    
    /// <summary>
    /// ID索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 显示划分
    /// </summary>
    public int Dis;
    
    /// <summary>
    /// 商城类型
    /// </summary>
    public int ShopType;
    
    /// <summary>
    /// 消耗货币
    /// </summary>
    public int Currency;
    
    /// <summary>
    /// 开放等级
    /// </summary>
    public int Level;
    
    /// <summary>
    /// 小类分页
    /// </summary>
    public string Type;
    
    /// <summary>
    /// 物品ID
    /// </summary>
    public int ItemId;
    
    /// <summary>
    /// 出售数量
    /// </summary>
    public int Count;
    
    /// <summary>
    /// 原价
    /// </summary>
    public int Price;
    
    /// <summary>
    /// 现价
    /// </summary>
    public int DiscountPrice;
    
    /// <summary>
    /// 限购方式
    /// </summary>
    public string Buy;
    
    public override int GetID()
    {
return ID ;
    }
}
