//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class GemTable : BaseTxtTable<GemTable>
{
    
    public string XlsxMapping = "Item.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 宝石类型
    /// </summary>
    public int GemType;
    
    /// <summary>
    /// 宝石属性
    /// </summary>
    public string GemAttr;
    
    /// <summary>
    /// 升级后宝石ID
    /// </summary>
    public int LevelUp;
    
    /// <summary>
    /// 宝石升级经验消耗
    /// </summary>
    public int GemExp;
    
    /// <summary>
    /// 吞噬获得经验
    /// </summary>
    public int ResolveExp;
    
    public override int GetID()
    {
return ID ;
    }
}
