//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class ItemTable : BaseTxtTable<ItemTable>
{
    
    public string XlsxMapping = "Item.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 物品名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 物品短描述
    /// </summary>
    public string ItemTypeText;
    
    /// <summary>
    /// 物品长描述
    /// </summary>
    public string ItemText;
    
    /// <summary>
    /// 物品icon
    /// </summary>
    public string ResId;
    
    /// <summary>
    /// 物品等级
    /// </summary>
    public int ItemLevel;
    
    /// <summary>
    /// 职业需求
    /// </summary>
    public int Occupation;
    
    /// <summary>
    /// 物品品质
    /// </summary>
    public int ItemQuality;
    
    /// <summary>
    /// 物品类型
    /// </summary>
    public int ItemType;
    
    /// <summary>
    /// 背包分页
    /// </summary>
    public int ItemClassify;
    
    /// <summary>
    /// 物品背包排序
    /// </summary>
    public int Sort;
    
    /// <summary>
    /// 物品使用读条时间
    /// </summary>
    public int CostTime;
    
    /// <summary>
    /// 使用效果
    /// </summary>
    public string UseEffect;
    
    /// <summary>
    /// 批量使用方式
    /// </summary>
    public int Batch;
    
    /// <summary>
    /// 使用次数
    /// </summary>
    public string UseCount;
    
    /// <summary>
    /// 获得自动提醒使用
    /// </summary>
    public int Remind;
    
    /// <summary>
    /// 叠加上限
    /// </summary>
    public int Stackable;
    
    /// <summary>
    /// 是否可丢弃
    /// </summary>
    public int Discard;
    
    /// <summary>
    /// 附加按钮显示
    /// </summary>
    public string OtherEffect;
    
    /// <summary>
    /// 掉落音效
    /// </summary>
    public string Sound;
    
    /// <summary>
    /// 掉落模型
    /// </summary>
    public string Model;
    
    /// <summary>
    /// 掉落品质特效
    /// </summary>
    public string QualityEffect;
    
    /// <summary>
    /// 掉落公告
    /// </summary>
    public int Announcement;
    
    /// <summary>
    /// 能否放入仓库
    /// </summary>
    public int Warehouse;
    
    /// <summary>
    /// 是否绑定
    /// </summary>
    public int bind;
    
    /// <summary>
    /// 对应物品ID
    /// </summary>
    public int NoBindId;
    
    /// <summary>
    /// 是否来源于强化
    /// </summary>
    public int Intensify;
    
    public override int GetID()
    {
return ID ;
    }
}
