//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class LanguageTable : BaseTxtTable<LanguageTable>
{
    
    public string XlsxMapping = "text.xlsx";
    
    /// <summary>
    /// ID索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 提示类型
    /// </summary>
    public int Type;
    
    /// <summary>
    /// 弹窗信息
    /// </summary>
    public string Text;
    
    /// <summary>
    /// 拒绝倒计时
    /// </summary>
    public int Time;
    
    /// <summary>
    /// 提示文本内容
    /// </summary>
    public string Content;
    
    /// <summary>
    /// 显示位置
    /// </summary>
    public int Position;
    
    /// <summary>
    /// 显示频道
    /// </summary>
    public string Channel;
    
    public override int GetID()
    {
return ID ;
    }
}
