//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class MapNpc : BaseTxtTable<MapNpc>
{
    
    public string XlsxMapping = "Npc.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// NPC名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// NPC功能名称
    /// </summary>
    public string FunctionName;
    
    /// <summary>
    /// NPC称号
    /// </summary>
    public string Title;
    
    /// <summary>
    /// 地图
    /// </summary>
    public int Map;
    
    /// <summary>
    /// NPC所在位置
    /// </summary>
    public string xyz;
    
    /// <summary>
    /// 碰撞范围
    /// </summary>
    public float Range;
    
    /// <summary>
    /// NPC角度
    /// </summary>
    public string Angle;
    
    /// <summary>
    /// NPC可见类型
    /// </summary>
    public string VisualType;
    
    /// <summary>
    /// NPC打开方式
    /// </summary>
    public int Open;
    
    /// <summary>
    /// 功能类型
    /// </summary>
    public int Function;
    
    /// <summary>
    /// 类型名称
    /// </summary>
    public string TypeName;
    
    /// <summary>
    /// 功能参数
    /// </summary>
    public string FunctionParameter;
    
    /// <summary>
    /// 默认对白
    /// </summary>
    public string DefaultTalk;
    
    /// <summary>
    /// 模型资源
    /// </summary>
    public string ResId;
    
    /// <summary>
    /// 冒泡
    /// </summary>
    public string Bubbling;
    
    /// <summary>
    /// 小地图显示规则
    /// </summary>
    public int MapDisplay;
    
    public override int GetID()
    {
return ID ;
    }
}
