//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class MapPlantTable : BaseTxtTable<MapPlantTable>
{
    
    public string XlsxMapping = "Plant.xlsx";
    
    /// <summary>
    /// 主键
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 采集物ID
    /// </summary>
    public int PlantID;
    
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 头像
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// 采集耗时
    /// </summary>
    public int Remain;
    
    /// <summary>
    /// 采集时显示
    /// </summary>
    public string display;
    
    /// <summary>
    /// 地图
    /// </summary>
    public int Map;
    
    /// <summary>
    /// 坐标
    /// </summary>
    public string xyz;
    
    /// <summary>
    /// 模型编号
    /// </summary>
    public string ResId;
    
    /// <summary>
    ///  模型缩放
    /// </summary>
    public int Modelzoom;
    
    /// <summary>
    /// 朝向
    /// </summary>
    public string angle;
    
    /// <summary>
    /// 采集人数
    /// </summary>
    public int Number;
    
    /// <summary>
    /// 产出道具
    /// </summary>
    public int Item;
    
    /// <summary>
    /// 复活时间
    /// </summary>
    public int Revive;
    
    /// <summary>
    /// 是否冲突
    /// </summary>
    public int Conflict;
    
    /// <summary>
    /// 采集完成特效
    /// </summary>
    public int VisualEffects;
    
    public override int GetID()
    {
return ID ;
    }
}
