//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class MapTransferTable : BaseTxtTable<MapTransferTable>
{
    
    public string XlsxMapping = "MapTransfer.xlsx";
    
    /// <summary>
    /// ID索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 起始场景
    /// </summary>
    public int MapId;
    
    /// <summary>
    /// 起始坐标
    /// </summary>
    public string Xyz;
    
    /// <summary>
    /// 形状类型
    /// </summary>
    public int FormType;
    
    /// <summary>
    /// 形状参数
    /// </summary>
    public string Form;
    
    /// <summary>
    /// 传送特效
    /// </summary>
    public string TeleporterEffect;
    
    /// <summary>
    /// 特效角度
    /// </summary>
    public string EffectAngle;
    
    /// <summary>
    /// 延迟时间
    /// </summary>
    public int DelayTime;
    
    /// <summary>
    /// 目标区域
    /// </summary>
    public int MapRegionId;
    
    /// <summary>
    /// 自身特效
    /// </summary>
    public string Effect;
    
    public override int GetID()
    {
return ID ;
    }
}
