//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class MatchingTable : BaseTxtTable<MatchingTable>
{
    
    public string XlsxMapping = "Battleground.xlsx";
    
    /// <summary>
    /// ID索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 战斗力阶段
    /// </summary>
    public string FC;
    
    /// <summary>
    /// 匹配参数1
    /// </summary>
    public string Parameter1;
    
    /// <summary>
    /// 匹配参数2
    /// </summary>
    public string Parameter2;
    
    public override int GetID()
    {
return ID ;
    }
}
