//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class MonsterTable : BaseTxtTable<MonsterTable>
{
    
    public string XlsxMapping = "Monster.xlsx";
    
    /// <summary>
    /// 怪物ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 怪物名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 怪物类别
    /// </summary>
    public int Type;
    
    /// <summary>
    /// 头像
    /// </summary>
    public int Head;
    
    /// <summary>
    /// 模型编号
    /// </summary>
    public string ResId;
    
    /// <summary>
    ///  模型缩放
    /// </summary>
    public float Modelzoom;
    
    /// <summary>
    /// 血条层数
    /// </summary>
    public int BloodNum;
    
    /// <summary>
    /// 重生规则
    /// </summary>
    public int Birthrule;
    
    /// <summary>
    /// 任务是否共享
    /// </summary>
    public int Isshare;
    
    /// <summary>
    /// 技能释放ID
    /// </summary>
    public string SkillReleaseId;
    
    /// <summary>
    /// 尸体时间
    /// </summary>
    public int Corpse;
    
    /// <summary>
    /// 重生周期
    /// </summary>
    public int Revive;
    
    /// <summary>
    /// 通用AIID
    /// </summary>
    public int baseAiID;
    
    /// <summary>
    /// 怪物等级
    /// </summary>
    public int MonsterLevel;
    
    /// <summary>
    /// 属性组id
    /// </summary>
    public int BaseAttribute;
    
    /// <summary>
    /// 掉落组ID
    /// </summary>
    public string DropGroupID;
    
    /// <summary>
    /// 说话
    /// </summary>
    public string bubble;
    
    /// <summary>
    /// 说话频率
    /// </summary>
    public int frequency;
    
    /// <summary>
    /// 小地图显示
    /// </summary>
    public int MapDisplay;
    
    public override int GetID()
    {
return ID ;
    }
}
