//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class OpenSystemTable : BaseTxtTable<OpenSystemTable>
{
    
    public string XlsxMapping = "System.xlsx";
    
    /// <summary>
    /// ID索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 系统ID
    /// </summary>
    public int System;
    
    /// <summary>
    /// 系统名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 系统icon
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// 等级开启
    /// </summary>
    public int Level;
    
    /// <summary>
    /// 任务开启
    /// </summary>
    public int Task;
    
    /// <summary>
    /// 开启是否提示
    /// </summary>
    public int Hint;
    
    /// <summary>
    /// 所在窗口
    /// </summary>
    public string Window;
    
    /// <summary>
    /// 按钮路径
    /// </summary>
    public string BtnPath;
    
    /// <summary>
    /// 飞入路径
    /// </summary>
    public string FlyPath;
    
    public override int GetID()
    {
return ID ;
    }
}
