//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class ParameterTable : BaseTxtTable<ParameterTable>
{
    
    public string XlsxMapping = "parameter.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 参数1
    /// </summary>
    public int IntVar;
    
    /// <summary>
    /// 参数2
    /// </summary>
    public string IntVars;
    
    /// <summary>
    /// 参数3
    /// </summary>
    public string StringVar;
    
    /// <summary>
    /// 参数4
    /// </summary>
    public string StringVars;
    
    /// <summary>
    /// 参数5
    /// </summary>
    public float FloatVar;
    
    /// <summary>
    /// 参数6
    /// </summary>
    public string FloatVars;
    
    public override int GetID()
    {
return ID ;
    }
}
