//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class PvpSeasonTable : BaseTxtTable<PvpSeasonTable>
{
    
    public string XlsxMapping = "PvpSmall.xlsx";
    
    /// <summary>
    /// ID
    /// </summary>
    public int Id;
    
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 升段星数
    /// </summary>
    public int Star;
    
    /// <summary>
    /// 所需战场积分
    /// </summary>
    public int NeedScore;
    
    /// <summary>
    /// 对应段位ICON
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// 赛季奖励物品
    /// </summary>
    public int RewardItem;
    
    /// <summary>
    /// 奖励发放时间
    /// </summary>
    public int RewardTime;
    
    /// <summary>
    /// 赛季结束是否清分
    /// </summary>
    public int IsClear;
    
    /// <summary>
    /// 阶段奖励邮件标题
    /// </summary>
    public string MailTitle;
    
    /// <summary>
    /// 阶段奖励邮件标题
    /// </summary>
    public string MailContent;
    
    public override int GetID()
    {
return Id ;
    }
}
