//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class PvpTable : BaseTxtTable<PvpTable>
{
    
    public string XlsxMapping = "PvpSmall.xlsx";
    
    /// <summary>
    /// ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 对战类型
    /// </summary>
    public string Type;
    
    /// <summary>
    /// 对战人数
    /// </summary>
    public int VS;
    
    /// <summary>
    /// 等级差值
    /// </summary>
    public int LevelValue;
    
    /// <summary>
    /// 是否开启组队
    /// </summary>
    public string CanMakeTeam;
    
    /// <summary>
    /// 是否惩罚
    /// </summary>
    public string Punishment;
    
    /// <summary>
    /// 复活
    /// </summary>
    public string revive;
    
    /// <summary>
    /// 是否加入机器人
    /// </summary>
    public int IsRobotIn;
    
    /// <summary>
    /// 平均积分
    /// </summary>
    public int Ccpa;
    
    /// <summary>
    /// K
    /// </summary>
    public int K;
    
    /// <summary>
    /// K增加值
    /// </summary>
    public int KInc;
    
    /// <summary>
    /// 是否用Kmax
    /// </summary>
    public int UseKMax;
    
    /// <summary>
    /// K
    /// </summary>
    public int Kper;
    
    /// <summary>
    /// K增加值
    /// </summary>
    public int Kperinc;
    
    /// <summary>
    /// 间隔时间
    /// </summary>
    public int Interval;
    
    /// <summary>
    /// 是否用Kmax
    /// </summary>
    public int UseKperMax;
    
    /// <summary>
    /// 准备超时
    /// </summary>
    public int PrepareTime;
    
    /// <summary>
    /// 战斗开始时间
    /// </summary>
    public int BattleCountdown;
    
    public override int GetID()
    {
return ID ;
    }
}
