//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class SlotUpgradeTable : BaseTxtTable<SlotUpgradeTable>
{
    
    public string XlsxMapping = "Slot.xlsx";
    
    /// <summary>
    /// 索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 普攻技能升级消耗
    /// </summary>
    public string UpgradeCost;
    
    /// <summary>
    /// 获得属性
    /// </summary>
    public string Property;
    
    /// <summary>
    /// 技能槽1
    /// </summary>
    public string UpgradeCost1;
    
    /// <summary>
    /// 获得属性1
    /// </summary>
    public string Property1;
    
    /// <summary>
    /// 技能槽2
    /// </summary>
    public string UpgradeCost2;
    
    /// <summary>
    /// 获得属性2
    /// </summary>
    public string Property2;
    
    /// <summary>
    /// 技能槽3
    /// </summary>
    public string UpgradeCost3;
    
    /// <summary>
    /// 获得属性3
    /// </summary>
    public string Property3;
    
    /// <summary>
    /// 技能槽4
    /// </summary>
    public string UpgradeCost4;
    
    /// <summary>
    /// 获得属性4
    /// </summary>
    public string Property4;
    
    /// <summary>
    /// 技能槽5
    /// </summary>
    public string UpgradeCost5;
    
    /// <summary>
    /// 获得属性5
    /// </summary>
    public string Property5;
    
    public override int GetID()
    {
return ID ;
    }
}
