//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class TaskTable : BaseTxtTable<TaskTable>
{
    
    public string XlsxMapping = "Task.xlsx";
    
    /// <summary>
    /// 序号
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 任务名称
    /// </summary>
    public string name;
    
    /// <summary>
    /// 类型
    /// </summary>
    public int type;
    
    /// <summary>
    /// 类型顺序
    /// </summary>
    public int typeorder;
    
    /// <summary>
    /// 阵营
    /// </summary>
    public int camp;
    
    /// <summary>
    /// 前置任务
    /// </summary>
    public int pretask;
    
    /// <summary>
    /// 后置任务
    /// </summary>
    public int Next;
    
    /// <summary>
    /// 领取等级
    /// </summary>
    public int level;
    
    /// <summary>
    /// 最高可领取等级
    /// </summary>
    public int maxlevel;
    
    /// <summary>
    /// 起始npc
    /// </summary>
    public int startnpc;
    
    /// <summary>
    /// 结束npc
    /// </summary>
    public int endnpc;
    
    /// <summary>
    /// 接受任务获得道具
    /// </summary>
    public string itemsreceive;
    
    /// <summary>
    /// 任务经验
    /// </summary>
    public int exp;
    
    /// <summary>
    /// 道具奖励
    /// </summary>
    public string rewarditems;
    
    /// <summary>
    /// 掉落组ID
    /// </summary>
    public string DropGroupID;
    
    /// <summary>
    ///  描述
    /// </summary>
    public string desc;
    
    /// <summary>
    /// 详细描述
    /// </summary>
    public string detaileddesc;
    
    /// <summary>
    /// 任务类型
    /// </summary>
    public int condition;
    
    /// <summary>
    /// 完成条件描述
    /// </summary>
    public string request;
    
    /// <summary>
    /// 自动接取
    /// </summary>
    public int AutoReceive;
    
    /// <summary>
    /// 自动完成
    /// </summary>
    public int AutoFinish;
    
    /// <summary>
    /// 任务直接进副本
    /// </summary>
    public int dungeon;
    
    /// <summary>
    /// 播放动画
    /// </summary>
    public int PlayMove;
    
    /// <summary>
    /// 接受任务传送地图
    /// </summary>
    public int MapRegionID;
    
    /// <summary>
    /// 任务标签
    /// </summary>
    public string tga;
    
    /// <summary>
    /// 等级不足是否显示
    /// </summary>
    public int is_show;
    
    /// <summary>
    /// 寻路ID
    /// </summary>
    public int Findpath;
    
    public override int GetID()
    {
return ID ;
    }
}
