//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class TasktalkTable : BaseTxtTable<TasktalkTable>
{
    
    public string XlsxMapping = "Task.xlsx";
    
    /// <summary>
    /// 序号
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 任务ID
    /// </summary>
    public int taskid;
    
    /// <summary>
    /// 说话类型
    /// </summary>
    public string speaktype;
    
    /// <summary>
    /// 阶段
    /// </summary>
    public int stage;
    
    /// <summary>
    /// 对话顺序
    /// </summary>
    public int order;
    
    /// <summary>
    /// 说话内容
    /// </summary>
    public string speakdesc;
    
    public override int GetID()
    {
return ID ;
    }
}
