//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class TimeLimitTable : BaseTxtTable<TimeLimitTable>
{
    
    public string XlsxMapping = "Item.xlsx";
    
    /// <summary>
    /// 序号
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 道具时限
    /// </summary>
    public int ItemLimit;
    
    /// <summary>
    /// 时限参数
    /// </summary>
    public string LimitParameter;
    
    public override int GetID()
    {
return ID ;
    }
}
