//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class TriggerTable : BaseTxtTable<TriggerTable>
{
    
    public string XlsxMapping = "Skill.xlsx";
    
    /// <summary>
    /// 触发器ID
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 持续时间（毫秒）
    /// </summary>
    public string ContinueTime;
    
    /// <summary>
    /// 触发CD（毫秒）
    /// </summary>
    public int Interval;
    
    /// <summary>
    /// 起效次数
    /// </summary>
    public int Count;
    
    /// <summary>
    /// 触发条件
    /// </summary>
    public string NeedType;
    
    /// <summary>
    /// 触发方式
    /// </summary>
    public int TriggerType;
    
    /// <summary>
    /// 触发参数
    /// </summary>
    public string Parameter;
    
    /// <summary>
    /// 触发概率（万分率）
    /// </summary>
    public string TriggerProbability;
    
    /// <summary>
    /// buff的ID
    /// </summary>
    public string BuffID;
    
    public override int GetID()
    {
return ID ;
    }
}
