//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



public class TroopsTable : BaseTxtTable<TroopsTable>
{
    
    public string XlsxMapping = "Troops.xlsx";
    
    /// <summary>
    /// ID索引
    /// </summary>
    public int ID;
    
    /// <summary>
    /// 目标大类
    /// </summary>
    public int BigType;
    
    /// <summary>
    /// 目标大类名称
    /// </summary>
    public string BigName;
    
    /// <summary>
    /// 目标小类
    /// </summary>
    public int Type;
    
    /// <summary>
    /// 小类名称
    /// </summary>
    public string Name;
    
    /// <summary>
    /// 目标调用内容
    /// </summary>
    public string Target;
    
    /// <summary>
    /// 类型图标
    /// </summary>
    public string Icon;
    
    /// <summary>
    /// 等级段区间
    /// </summary>
    public string Level;
    
    /// <summary>
    /// 等级区间匹配方式
    /// </summary>
    public int MateLevel;
    
    public override int GetID()
    {
return ID ;
    }
}
