//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8669
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.IO;



[System.SerializableAttribute()]
public class Bag1Table : BaseTable<Bag1Table>
{

    public string XlsxMapping = "Bag.xlsx";

    /// <summary>
    /// 背包格子ID
    /// </summary>
    public int ID;

    /// <summary>
    /// 开启等级
    /// </summary>
    public int OpenLevel;

    /// <summary>
    /// 开启消耗
    /// </summary>
    public int Consume;

    public static void DecodeList(BinaryReader br)
    {
        int dataCount = br.ReadInt32();
        for (int i = 0; i < dataCount; i++)
        {
            Bag1Table _bagtable = new Bag1Table();
            _bagtable.Deserialize(br);
            list.Add(_bagtable);
            dictionary[_bagtable.GetID()] = _bagtable;
        }
        //TableEntity.TableListByKey["BagTable"] = list;
        //TableEntity.TableDicByKey["BagTable"] = dictionary;
    }

    public override object GetKey(string key)
    {
        switch (key)
        {
            case "ID":
                return ID;
            case "OpenLevel":
                return OpenLevel;
            case "Consume":
                return Consume;
        }
        return null;
    }

    public override void Write(OfficeOpenXml.ExcelWorksheet ew, int row)
    {
        ew.SetValue(row, 1, ID);
        ew.SetValue(row, 2, OpenLevel);
        ew.SetValue(row, 3, Consume);
    }

    public override int GetID()
    {
        return ID;
    }

    public override void Serialize(BinaryWriter bw)
    {
        bw.Write(ID);
        bw.Write(OpenLevel);
        bw.Write(Consume);
    }

    public override void Deserialize(BinaryReader br)
    {
        ID = br.ReadInt32();
        OpenLevel = br.ReadInt32();
        Consume = br.ReadInt32();
    }
}
